spring:
  application:
    name: vertex-marketplace

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vertex}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# Custom JWT configuration
application:
  security:
    jwt:
      # Minimally 256-bit strong base64 key
      secret-key: ${JWT_SECRET:d2VydHl1aW9wYXNkZmdoamtsenhjdmJubTEyMzQ1Njc4OTBxd2VydHl1aW9wYXNkZmdoamtsenhjdmJubTEyMzQ1Njc4OTA=}
      # Expiration time in milliseconds (default: 1 day)
      expiration: ${JWT_EXPIRATION:86400000}
